### ISSUE TITLE
 Symbol’s value as variable is void: my-stuff-dir

### ISSUE THREAD

**Issue by maikol-solis** [Idorobots/gamify-el#8]
Basically, `my-stuff-dir` is hardcoded here: 

https://github.com/Idorobots/gamify-el/blob/0543e5dfb11dc32a3f3d5b634b04ccd01a7d4be6/gamify.el#L620

**Comment by Idorobots** [comment]
Ah yeah, I goofed it up when I "fixed" broken notifications after an upgrade to Emacs. Will fix it shortly together with #7

**Comment by Idorobots** [comment]
I re-added `gamify-notification-function` setting along with `gamify-notification-xp-icon-path` that can be customized. Con you please set these to whatever you'd like to use (e.g. `notify-send` and `nil`) to see if that works now on your end?

**Comment by maikol-solis** [comment]
Thanks! Now it works! 

I set `gamify-notification-function` to `nil` because I'm on MacOS and I don't know what function I need to put there.

**Comment by Idorobots** [comment]
Yep, that is the default right now as it's system-dependent. :) [There are some options for MacOS it seems.](https://christiantietze.de/posts/2019/12/emacs-notifications/) but I don't have the means to test that.
